/* Text editor types */
const CHANGE_STATE_POST: string = "CHANGE_STATE_POST";
const CHANGE_TAGS_POST: string = "CHANGE_TAGS_POST";
const CHANGE_CONTENT_POST: string = "CHANGE_CONTENT_POST";
const CHANGE_IMAGE_POST: string = "CHANGE_IMAGE_POST";
const REQUEST_CREATE_POST: string = "REQUEST_CREATE_POST";
const SUCCESS_CREATE_POST: string = "SUCCESS_CREATE_POST";
const ERROR_CREATE_POST: string = "ERROR_CREATE_POST";
const IS_LOGIN: string = "IS_LOGIN";
const IS_LOGOUT: string = "IS_LOGOUT";
const FETCH_WISHLIST: string = "FETCH_WISHLIST";
const TOGGLE_WISHLIST: string = "TOGGLE_WISHLIST";

export {
  CHANGE_STATE_POST,
  CHANGE_TAGS_POST,
  CHANGE_CONTENT_POST,
  CHANGE_IMAGE_POST,
  REQUEST_CREATE_POST,
  SUCCESS_CREATE_POST,
  ERROR_CREATE_POST,
  IS_LOGIN,
  IS_LOGOUT,
  FETCH_WISHLIST,
  TOGGLE_WISHLIST,
};
